spring:  
  application:
    name: client-service

---
spring:
  profiles: zone1
eureka:
  instance:
    metadataMap:
      zone: zone1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8764/eureka/
server:  
  port: ${PORT:9100}

---
spring:
  profiles: zone2
eureka:
  instance:
    metadataMap:
      zone: zone2
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:  
  port: ${PORT:9110}
  
---
spring:
  profiles: zone3
eureka:
  instance:
    metadataMap:
      zone: zone3
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
server:  
  port: ${PORT:9120}